### ISSUE TITLE
Unknown custom metadata item kind: 7

### ISSUE THREAD

**Issue by michael-x** [SymbolSource/SymbolSource.Community#32]
When trying to push a symbol package to SymbolServer that contains an assembly that has been created with the new MSBuild 14 toolset, we are getting the a 'Microsoft.Cci.Pdb.PdbDebugException' with the following stack trace:

```
Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings)
   at SymbolSource.Processing.Basic.ManagedSourceExtractor.ReadSources(Stream peStream, Stream pdbStream)
   at SymbolSource.Processing.Basic.Projects.SourceDiscover.&lt;FindSources&gt;d__c.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.&lt;GetEnumerator&gt;d__0.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.BuildBinaryInfo(IAddInfo addInfo, IList`1 fileInfos, IPackageEntry binaryFileInfo)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processing.Basic.Projects.AddInfoBuilder.Build(IPackageFile directoryInfo)
   at SymbolSource.Server.Basic.BasicBackend.CreateJob(PackageProject metadata, Byte[] data)
   at SymbolSource.Server.Basic.BasicBackend.UploadPackage(PackageProject package, String packageFormat, Byte[] packageData, Byte[] symbolPackageData)
   at SymbolSource.Gateway.Core.GatewayManager.PerformUpload(Caller caller, PackageProject packageProject, String path)
   at SymbolSource.Gateway.Core.GatewayManager.Upload(Caller caller, Stream stream, String company, String repository)" time="2015-07-24T09:03:14.7251102Z">
```

I've seen that there have been similar reports for SymbolSource.org which have been resolved:
- https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/40
- https://github.com/aspnet/dnx/issues/1690

Unfortunately there has been no update to the SymbolSource.Server.Basic for a while.

**Comment by amazingant** [comment]
Second this. I'm getting similar results with metadata item kind 6, pushing a VB project built against MSBuild 14. Trying to resolve this by just updating all nuget packages has successfully broken the entire project. :)

**Comment by vadimi** [comment]
I also see the same issue with our private NuGet server based on SymbolSource.Server.Basic. Any chance we can get some more details on what's going on?

**Comment by jmwheeler** [comment]
Having the same issue as well.  Any update coming?

**Comment by Addisco** [comment]
I have the same issue, too! Is anyone invastigating in this?
It does not seem like this project is maintained, since the issue has been fixed for symbolsource.org.

**Comment by amazingant** [comment]
I know it isn't what any of us were hoping for as we commented here, but in the last two months I've moved my team's code to use [SourceLink][1] instead. It's open-source on [GitHub][2] as well, and there's a port named [GitLink][3] written in C# in case anyone is afraid of using a tool written in F# (don't be).

The concept with these two tools is that you distribute `.pdb` files with your executables, and when building a release, SourceLink is called and adds some extra instructions into the `.pdb` files. When you go to debug a crash dump or whatnot and Visual Studio can't find matching source code on your local system, it looks at those instructions and follows a URL to get the source code.

Both projects are intended to be used with projects hosted publicly on GitHub (or elsewhere). If your code is hosted privately on GitHub like some of mine is, after setting-up a [proxy][4], the process has worked very well for me: when debugging one of these for the first time, Visual Studio pops up a dialog asking for my GitHub credentials, I give it an access token as my password, and everything runs smoothly from there.

If your source code is hosted internally and you can get to it via HTTP, you can just use that instead. If you do, be aware: The URL format needs to allow specifying the git commit to get the source for (so Visual Studio receives the correct revision of each file), and the URL cannot contain GET parameters. Most importantly, the server needs to return files with the same line-endings that the executable was compiled against (`\r\n` vs `\n`). Visual Studio validates a checksum for each file before it will accept it, and those checksums won't match if, say, your build server clones your source as `\r\n`, but your source server returns files with `\n`.

[1]: http://ctaggart.github.io/SourceLink/
[2]: https://github.com/ctaggart/SourceLink
[3]: https://github.com/GitTools/GitLink
[4]: https://github.com/ctaggart/SourceLink-Proxy

**Comment by michael-x** [comment]
@amazingant: thanks for the suggestion. We've now gone a similar route using svnindex from the Windows 10 Kit Debugging Tools to perform source indexing against our Subversion server for our internal packages. Needed to modify svn.pm slightly, but now it works properly.

Three downsides:
a) You need to give permission to the tool downloading the source (i.e. cmd /k svn.exe).
b) You need SVN.exe in the path on the debugging machine (probably there already, but nevertheless).
c) You are bound to your revision control system. If you want to retire that at some point in time, debugging stops working.

Therefore it would still be great to have a proper (private) source and symbol server.

**Comment by mwijnands** [comment]
I managed to fix this. I made a NuGet package with a slightly modified Microsoft.Cci.Metadata: https://www.nuget.org/packages/CustomMetadataFix.Microsoft.Cci.Metadata/. When you install that instead of SymbolSource.Microsoft.Cci.Metadata, you can succesfully publish PDB's created with MsBuild 14.0 tools.

The fix I applied is this one, from the official repository: https://ccimetadata.codeplex.com/SourceControl/changeset/73073. I applied this to the source of https://github.com/SymbolSource/Microsoft.Cci.Metadata as it was on 8 september 2011, because that's when the SymbolSource.Microsoft.Cci.Metadata package was made.

It took me a while but I hope it helps someone. It appears this project is really dead though so it would be wise to find something else. Turned out we don't even need this as TFS can already publish symbols to a network share, and links to the source files in TFS.

**Comment by Allon-Guralnek** [comment]
@mwijnands: It does help. Thanks for this, our symbol server now works with MSBuild 14.

**Comment by MichaelCommo** [comment]
@mwijnands thank you for building/sharing that package.  We, too, can now use our symbolsource  basic server with msbuild14.

**Comment by TripleEmcoder** [comment]
This project is deprecated in favor of https://github.com/SymbolSource/SymbolSource - closing as won't fix.
